#!/usr/bin/env python3
"""Build the one-response LWAI fallback deterministically from owned transport capsules."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PLAN_PATH = ROOT / "engine/standalone/plan.json"
MANIFEST_PATH = ROOT / "engine/MANIFEST.json"


def fail(message: str) -> None:
    print(f"FAIL: compiled bootstrap: {message}")
    raise SystemExit(1)


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def expected_module_digests(manifest: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for module in manifest.get("modules") or []:
        module_id = module.get("module_id")
        digest = (module.get("integrity") or {}).get("digest")
        if not module_id or not digest:
            fail("manifest module missing module_id/integrity.digest")
        out[module_id] = digest
    return out


def validate_plan(plan: dict, manifest: dict) -> None:
    for key in ("engine_version", "engine_api_version", "schema_version"):
        if plan.get(key) != manifest.get(key):
            fail(f"plan {key} does not match MANIFEST")

    if manifest.get("channel") != "Production":
        fail("MANIFEST channel is not Production")
    if manifest.get("sanitized") is not True:
        fail("MANIFEST sanitized must be true")
    if manifest.get("account_state_included") is not False:
        fail("MANIFEST account_state_included must be false")

    expected = expected_module_digests(manifest)
    actual = plan.get("source_module_digests") or {}
    if actual != expected:
        missing = sorted(set(expected) - set(actual))
        extra = sorted(set(actual) - set(expected))
        changed = sorted(
            module_id
            for module_id in set(expected) & set(actual)
            if expected[module_id] != actual[module_id]
        )
        fail(
            "source-module fingerprint mismatch; compact projection requires review "
            f"(missing={missing}, extra={extra}, changed={changed})"
        )

    module_ids = set(expected)
    capsules = plan.get("capsules") or []
    if not capsules:
        fail("plan has no capsules")

    seen_paths: set[str] = set()
    owned: set[str] = set()
    for capsule in capsules:
        path = capsule.get("path")
        owners = capsule.get("owners") or []
        if not path or path in seen_paths:
            fail(f"invalid/duplicate capsule path: {path!r}")
        seen_paths.add(path)
        if not owners:
            fail(f"capsule {path} has no owners")
        unknown = sorted(set(owners) - module_ids)
        if unknown:
            fail(f"capsule {path} has unknown owners: {unknown}")
        owned.update(owners)
        capsule_path = ROOT / path
        if not capsule_path.is_file():
            fail(f"missing capsule: {path}")
        body = capsule_path.read_text(encoding="utf-8")
        if body.startswith("\n") or body.endswith("\n"):
            fail(f"capsule must not have leading/trailing newline: {path}")
        if "ACCOUNT STATE INCLUDED: YES" in body:
            fail(f"capsule leaks account-state marker: {path}")

    unowned = sorted(module_ids - owned)
    if unowned:
        fail(f"manifest modules without compact-projection ownership: {unowned}")


def render_header(plan: dict, manifest: dict) -> str:
    header = plan.get("header") or {}
    if header.get("sanitized") is not True or header.get("account_state_included") is not False:
        fail("plan header privacy identity invalid")

    lines = [
        header.get("title") or "LAST WAR ACCOUNT INTELLIGENCE — COMPLETE PRODUCTION FALLBACK",
        f"engine_version: {manifest['engine_version']}",
        f"engine_api_version: {manifest['engine_api_version']}",
        f"format: {header.get('format') or 'UTF-8 plain text'}",
        "SANITIZED: YES",
        "ACCOUNT STATE INCLUDED: NO",
        f"runtime_mode: {header.get('runtime_mode') or 'standalone_fallback'}",
    ]
    return "\n".join(lines)


def compile_bootstrap() -> str:
    plan = read_json(PLAN_PATH)
    manifest = read_json(MANIFEST_PATH)
    validate_plan(plan, manifest)

    pieces = [render_header(plan, manifest)]
    for capsule in plan["capsules"]:
        pieces.append((ROOT / capsule["path"]).read_text(encoding="utf-8"))
    return "\n\n".join(pieces)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail unless generated bytes equal the checked-in artifact")
    parser.add_argument("--stdout", action="store_true", help="write generated artifact to stdout")
    parser.add_argument("--output", help="override output path")
    args = parser.parse_args()

    plan = read_json(PLAN_PATH)
    output_path = ROOT / (args.output or plan.get("output") or "engine/BOOTSTRAP_FULL.txt")
    generated = compile_bootstrap()
    generated_bytes = generated.encode("utf-8")
    digest = hashlib.sha256(generated_bytes).hexdigest()

    if args.check:
        if not output_path.is_file():
            fail(f"checked artifact missing: {output_path.relative_to(ROOT)}")
        existing = output_path.read_bytes()
        if existing != generated_bytes:
            print(
                f"generated={len(generated_bytes)} B sha256={digest}; "
                f"checked_in={len(existing)} B sha256={hashlib.sha256(existing).hexdigest()}"
            )
            fail("checked-in BOOTSTRAP_FULL.txt differs from deterministic compiler output")
        print(
            f"PASS: compiled single-response artifact is exact: "
            f"{len(generated_bytes)} B sha256={digest}"
        )
        return

    if args.stdout:
        sys.stdout.write(generated)
        return

    output_path.write_bytes(generated_bytes)
    print(
        f"WROTE: {output_path.relative_to(ROOT)} "
        f"{len(generated_bytes)} B sha256={digest}"
    )


if __name__ == "__main__":
    main()
